# Generated by Django 6.0.2 on 2026-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1, help_text="Capacidade máxima de animais."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shelter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
