# Generated by Django 6.0.2 on 2026-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available"), ("ADOPTED", "Adopted")],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
    ]
